import "dotenv/config";
import mongoose from "mongoose";
import { env } from "../src/lib/env.js";
import { User } from "../src/models/User.js";
import { Product } from "../src/models/Product.js";
import bcrypt from "bcrypt";

// ── Sample products ───────────────────────────────────────────────────────────

const PRODUCTS = [
  // ── Existing 12 ────────────────────────────────────────────────────────────
  {
    slug: "floral-wrap-dress",
    name: "Floral Wrap Dress",
    brand: "Zara",
    description: "A lightweight floral wrap dress perfect for spring outings. Features a V-neckline and adjustable waist tie.",
    price: 59.99,
    originalPrice: 89.99,
    images: ["https://placehold.co/600x800?text=Floral+Wrap+Dress"],
    stock: 42,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "ribbed-turtleneck-sweater",
    name: "Ribbed Turtleneck Sweater",
    brand: "COS",
    description: "A cozy ribbed turtleneck sweater crafted from a soft cotton-wool blend. Relaxed silhouette for effortless layering.",
    price: 79.00,
    images: ["https://placehold.co/600x800?text=Turtleneck+Sweater"],
    stock: 30,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "wide-leg-linen-trousers",
    name: "Wide Leg Linen Trousers",
    brand: "& Other Stories",
    description: "Breezy wide-leg trousers in breathable linen. High waist with an elastic back for all-day comfort.",
    price: 95.00,
    images: ["https://placehold.co/600x800?text=Linen+Trousers"],
    stock: 18,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "oversized-denim-jacket",
    name: "Oversized Denim Jacket",
    brand: "Levi's",
    description: "A classic oversized denim jacket with a vintage wash. Four-pocket styling and contrast stitching.",
    price: 110.00,
    images: ["https://placehold.co/600x800?text=Denim+Jacket"],
    stock: 25,
    category: ["women"],
    sizes: ["S", "M", "L", "XL"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "slim-fit-chinos",
    name: "Slim Fit Chinos",
    brand: "J.Crew",
    description: "Versatile slim-fit chinos made from stretch cotton. Ideal for smart-casual looks.",
    price: 69.50,
    images: ["https://placehold.co/600x800?text=Slim+Chinos"],
    stock: 60,
    category: ["men"],
    sizes: ["28", "30", "32", "34", "36"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "merino-crewneck-sweater",
    name: "Merino Crewneck Sweater",
    brand: "Uniqlo",
    description: "Fine-knit merino wool crewneck in a relaxed fit. Naturally temperature-regulating and itch-free.",
    price: 49.90,
    images: ["https://placehold.co/600x800?text=Merino+Crewneck"],
    stock: 55,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "oxford-button-down-shirt",
    name: "Oxford Button-Down Shirt",
    brand: "Ralph Lauren",
    description: "A timeless Oxford cloth button-down shirt. Chest pocket and signature embroidered logo.",
    price: 89.00,
    images: ["https://placehold.co/600x800?text=Oxford+Shirt"],
    stock: 40,
    category: ["men"],
    sizes: ["S", "M", "L", "XL"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "cargo-jogger-pants",
    name: "Cargo Jogger Pants",
    brand: "Carhartt WIP",
    description: "Relaxed cargo joggers with multiple utility pockets and an elasticated cuff. Durable ripstop fabric.",
    price: 120.00,
    originalPrice: 150.00,
    images: ["https://placehold.co/600x800?text=Cargo+Joggers"],
    stock: 22,
    category: ["men", "sale"],
    sizes: ["S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "leather-tote-bag",
    name: "Leather Tote Bag",
    brand: "Toteme",
    description: "A structured tote in full-grain leather. Spacious interior with zip pocket and magnetic snap closure.",
    price: 320.00,
    images: ["https://placehold.co/600x800?text=Leather+Tote"],
    stock: 10,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "wool-blend-scarf",
    name: "Wool Blend Scarf",
    brand: "Acne Studios",
    description: "A generously sized scarf in a wool-mohair blend. Fringe trim on both ends.",
    price: 180.00,
    originalPrice: 230.00,
    images: ["https://placehold.co/600x800?text=Wool+Scarf"],
    stock: 15,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "tortoise-sunglasses",
    name: "Tortoise Shell Sunglasses",
    brand: "Le Specs",
    description: "Round tortoise shell frames with UV400 polarised lenses. Lightweight and durable acetate construction.",
    price: 65.00,
    images: ["https://placehold.co/600x800?text=Sunglasses"],
    stock: 35,
    category: ["accessories", "new-arrivals"],
    sizes: ["One Size"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "canvas-baseball-cap",
    name: "Canvas Baseball Cap",
    brand: "Carhartt WIP",
    description: "Six-panel baseball cap in washed canvas. Adjustable strapback with metal buckle.",
    price: 35.00,
    images: ["https://placehold.co/600x800?text=Baseball+Cap"],
    stock: 80,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: null,
    isPublished: true,
  },

  // ── New 100 ────────────────────────────────────────────────────────────────

  // Women (40 items)
  {
    slug: "satin-midi-skirt",
    name: "Satin Midi Skirt",
    brand: "Reformation",
    description: "Elegant bias-cut satin midi skirt with a flattering wrap silhouette. Elasticated waistband for easy fit.",
    price: 128.00,
    images: ["https://placehold.co/600x800?text=Satin+Midi+Skirt"],
    stock: 20,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "cashmere-cardigan",
    name: "Cashmere Cardigan",
    brand: "Everlane",
    description: "Grade-A cashmere button-front cardigan with deep side pockets. Relaxed boxy fit, perfect for layering.",
    price: 198.00,
    originalPrice: 248.00,
    images: ["https://placehold.co/600x800?text=Cashmere+Cardigan"],
    stock: 14,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "cropped-blazer-ivory",
    name: "Cropped Blazer",
    brand: "Mango",
    description: "Tailored cropped blazer in a soft stretch fabric. Notch lapels, welt pockets, and a single-button front.",
    price: 85.00,
    images: ["https://placehold.co/600x800?text=Cropped+Blazer"],
    stock: 28,
    category: ["women"],
    sizes: ["XS", "S", "M", "L"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "pleated-midi-dress",
    name: "Pleated Midi Dress",
    brand: "Sandro",
    description: "Flowy pleated midi dress in lightweight georgette. V-neck with subtle ruching at the waist.",
    price: 215.00,
    images: ["https://placehold.co/600x800?text=Pleated+Midi+Dress"],
    stock: 16,
    category: ["women"],
    sizes: ["XS", "S", "M", "L"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "mom-jeans-straight",
    name: "High Rise Mom Jeans",
    brand: "Agolde",
    description: "Vintage-inspired high-rise mom jeans with a relaxed straight leg. Authentic worn-in wash and frayed hem.",
    price: 148.00,
    images: ["https://placehold.co/600x800?text=Mom+Jeans"],
    stock: 33,
    category: ["women"],
    sizes: ["24", "25", "26", "27", "28", "29", "30"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "knit-polo-shirt-women",
    name: "Knit Polo Shirt",
    brand: "Lacoste",
    description: "Classic pique polo shirt in a slim women's fit. Three-button placket with ribbed collar and cuffs.",
    price: 95.00,
    images: ["https://placehold.co/600x800?text=Knit+Polo"],
    stock: 45,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "trench-coat-women",
    name: "Classic Trench Coat",
    brand: "Burberry",
    description: "The iconic Burberry trench coat in water-resistant gabardine. Double-breasted with storm flaps and D-ring belt.",
    price: 1650.00,
    images: ["https://placehold.co/600x800?text=Trench+Coat"],
    stock: 6,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "slip-on-mule-heels",
    name: "Slip-On Mule Heels",
    brand: "Staud",
    description: "Sleek leather mule heels with an open toe and kitten heel. Padded insole for all-day comfort.",
    price: 275.00,
    originalPrice: 345.00,
    images: ["https://placehold.co/600x800?text=Mule+Heels"],
    stock: 12,
    category: ["women", "sale"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "ruffled-blouse",
    name: "Ruffled Silk Blouse",
    brand: "Isabel Marant",
    description: "Delicate silk blouse with cascading ruffle detail at the neckline. Relaxed fit with a curved hem.",
    price: 310.00,
    images: ["https://placehold.co/600x800?text=Ruffled+Blouse"],
    stock: 9,
    category: ["women"],
    sizes: ["XS", "S", "M", "L"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "paperbag-waist-shorts",
    name: "Paperbag Waist Shorts",
    brand: "& Other Stories",
    description: "High-waisted shorts with a paperbag tie waist and wide-leg cut. Lightweight linen-cotton fabric.",
    price: 65.00,
    images: ["https://placehold.co/600x800?text=Paperbag+Shorts"],
    stock: 38,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "bodycon-midi-dress",
    name: "Ribbed Bodycon Midi Dress",
    brand: "Skims",
    description: "Form-fitting ribbed midi dress in a sculpting stretch knit. Mock-neck with a seamless construction.",
    price: 88.00,
    images: ["https://placehold.co/600x800?text=Bodycon+Dress"],
    stock: 50,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "longline-blazer-check",
    name: "Longline Check Blazer",
    brand: "Theory",
    description: "Elegant longline blazer in a subtle check pattern. Single-button closure with patch pockets.",
    price: 485.00,
    originalPrice: 620.00,
    images: ["https://placehold.co/600x800?text=Longline+Blazer"],
    stock: 7,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "crochet-beach-cover",
    name: "Crochet Beach Cover-Up",
    brand: "Faithfull the Brand",
    description: "Hand-crocheted cotton beach cover-up with an open weave. Tassel hem and a relaxed silhouette.",
    price: 145.00,
    images: ["https://placehold.co/600x800?text=Crochet+Cover"],
    stock: 22,
    category: ["women", "new-arrivals"],
    sizes: ["XS/S", "M/L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "velvet-slip-dress",
    name: "Velvet Slip Dress",
    brand: "Reformation",
    description: "Luxurious crushed velvet slip dress with adjustable spaghetti straps and a subtle V-back.",
    price: 178.00,
    images: ["https://placehold.co/600x800?text=Velvet+Slip+Dress"],
    stock: 17,
    category: ["women"],
    sizes: ["XS", "S", "M", "L"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "high-waist-cycling-shorts",
    name: "High Waist Cycling Shorts",
    brand: "Lululemon",
    description: "High-waist Nulu cycling shorts in a four-way stretch fabric. Sweat-wicking and squat-proof.",
    price: 68.00,
    images: ["https://placehold.co/600x800?text=Cycling+Shorts"],
    stock: 65,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "linen-shirt-dress",
    name: "Linen Shirt Dress",
    brand: "H&M Conscious",
    description: "Relaxed shirt dress in 100% linen. Button-front with a belted waist and breast pockets.",
    price: 49.99,
    originalPrice: 69.99,
    images: ["https://placehold.co/600x800?text=Linen+Shirt+Dress"],
    stock: 30,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "tie-dye-maxi-skirt",
    name: "Tie-Dye Maxi Skirt",
    brand: "Free People",
    description: "Boho-inspired tie-dye maxi skirt in a crinkled cotton. Elasticated waist with a flowing silhouette.",
    price: 98.00,
    images: ["https://placehold.co/600x800?text=Tie+Dye+Skirt"],
    stock: 19,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "boyfriend-fit-jeans",
    name: "Boyfriend Fit Jeans",
    brand: "Levi's",
    description: "Classic boyfriend-cut jeans with a mid-rise waist and relaxed through the hip and thigh.",
    price: 89.99,
    images: ["https://placehold.co/600x800?text=Boyfriend+Jeans"],
    stock: 40,
    category: ["women"],
    sizes: ["24", "25", "26", "27", "28", "29", "30", "31"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "sequin-mini-skirt",
    name: "Sequin Mini Skirt",
    brand: "Rotate",
    description: "Statement all-over sequin mini skirt with an elasticated waist. Party-ready and effortlessly fun.",
    price: 155.00,
    images: ["https://placehold.co/600x800?text=Sequin+Skirt"],
    stock: 13,
    category: ["women"],
    sizes: ["XS", "S", "M", "L"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "oversized-graphic-tee-women",
    name: "Oversized Graphic Tee",
    brand: "Acne Studios",
    description: "Heavyweight cotton oversized tee with a minimalist graphic print. Dropped shoulders and a boxy fit.",
    price: 120.00,
    originalPrice: 160.00,
    images: ["https://placehold.co/600x800?text=Graphic+Tee"],
    stock: 35,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "smocked-sundress",
    name: "Smocked Sundress",
    brand: "Faithfull the Brand",
    description: "Sweet smocked sundress in a floral cotton. V-neck with adjustable tie straps and a tiered skirt.",
    price: 185.00,
    images: ["https://placehold.co/600x800?text=Smocked+Sundress"],
    stock: 14,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "sport-luxe-leggings",
    name: "Sport Luxe Leggings",
    brand: "Vuori",
    description: "Performance leggings in a buttery-soft stretch fabric. High-waist with a hidden pocket and mesh panels.",
    price: 98.00,
    images: ["https://placehold.co/600x800?text=Leggings"],
    stock: 55,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "bandeau-co-ord-set",
    name: "Bandeau Co-Ord Set",
    brand: "PrettyLittleThing",
    description: "Matching bandeau top and wide-leg trouser set in a textured fabric. Coordinated for effortless dressing.",
    price: 55.00,
    originalPrice: 78.00,
    images: ["https://placehold.co/600x800?text=Co-Ord+Set"],
    stock: 20,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "wool-cape-coat",
    name: "Wool Cape Coat",
    brand: "Max Mara",
    description: "Iconic princess-seamed cape coat in a double-faced camel wool. Impeccably tailored with a silk lining.",
    price: 1980.00,
    images: ["https://placehold.co/600x800?text=Cape+Coat"],
    stock: 4,
    category: ["women"],
    sizes: ["XS", "S", "M", "L"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "mesh-long-sleeve-top",
    name: "Sheer Mesh Top",
    brand: "Helmut Lang",
    description: "Subtle sheer mesh long-sleeve top with a relaxed fit. Layer over a bralette for an elevated look.",
    price: 175.00,
    images: ["https://placehold.co/600x800?text=Mesh+Top"],
    stock: 18,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "ponte-pencil-skirt",
    name: "Ponte Pencil Skirt",
    brand: "Theory",
    description: "Sleek ponte pencil skirt with a back slit for ease of movement. Office-ready and polished.",
    price: 145.00,
    images: ["https://placehold.co/600x800?text=Pencil+Skirt"],
    stock: 22,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "oversized-flannel-shirt-women",
    name: "Oversized Flannel Shirt",
    brand: "Pendleton",
    description: "Classic plaid flannel shirt in a cozy brushed cotton. Oversized fit with a curved shirttail hem.",
    price: 79.00,
    originalPrice: 105.00,
    images: ["https://placehold.co/600x800?text=Flannel+Shirt"],
    stock: 28,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "tailored-shorts-women",
    name: "Tailored Bermuda Shorts",
    brand: "COS",
    description: "Structured Bermuda shorts in a smooth stretch twill. Pleated front with side-seam pockets.",
    price: 75.00,
    images: ["https://placehold.co/600x800?text=Bermuda+Shorts"],
    stock: 32,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "maxi-halter-dress",
    name: "Halter Maxi Dress",
    brand: "Zimmermann",
    description: "Flowing halter maxi dress in a printed silk crepe. Adjustable neck ties and a subtle A-line skirt.",
    price: 495.00,
    images: ["https://placehold.co/600x800?text=Halter+Maxi+Dress"],
    stock: 8,
    category: ["women"],
    sizes: ["XS", "S", "M", "L"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "ballet-flats",
    name: "Classic Ballet Flats",
    brand: "Repetto",
    description: "The iconic Cendrillon ballet flat in supple kid leather. Hand-stitched French construction with a cushioned insole.",
    price: 220.00,
    originalPrice: 280.00,
    images: ["https://placehold.co/600x800?text=Ballet+Flats"],
    stock: 15,
    category: ["women", "sale"],
    sizes: ["35", "36", "37", "38", "39", "40", "41"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "cropped-hoodie-women",
    name: "Cropped Zip Hoodie",
    brand: "Champion",
    description: "Reverse-weave cropped zip hoodie in a heavyweight cotton blend. Embroidered logo and adjustable hood.",
    price: 65.00,
    images: ["https://placehold.co/600x800?text=Crop+Hoodie"],
    stock: 42,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "flared-denim-jeans",
    name: "Flared Denim Jeans",
    brand: "Frame",
    description: "High-rise flared jeans in a medium-wash denim. Elongating silhouette with a slight stretch for comfort.",
    price: 215.00,
    images: ["https://placehold.co/600x800?text=Flared+Jeans"],
    stock: 19,
    category: ["women"],
    sizes: ["24", "25", "26", "27", "28", "29", "30"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "knit-tank-top",
    name: "Ribbed Knit Tank",
    brand: "Skims",
    description: "Fitted ribbed knit tank in a soft stretch cotton. Scoop neck with a cropped length.",
    price: 42.00,
    images: ["https://placehold.co/600x800?text=Ribbed+Tank"],
    stock: 70,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "puffer-vest-women",
    name: "Puffer Vest",
    brand: "The North Face",
    description: "Lightweight 600-fill down puffer vest. Wind-resistant shell with a zip front and two hand pockets.",
    price: 149.00,
    originalPrice: 185.00,
    images: ["https://placehold.co/600x800?text=Puffer+Vest"],
    stock: 24,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "asymmetric-midi-dress",
    name: "Asymmetric Hem Midi Dress",
    brand: "Helmut Lang",
    description: "Architectural midi dress with an asymmetric hem. Minimalist design in a smooth ponte fabric.",
    price: 350.00,
    images: ["https://placehold.co/600x800?text=Asymmetric+Dress"],
    stock: 10,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "cotton-poplin-shirt-women",
    name: "Cotton Poplin Shirt",
    brand: "Uniqlo",
    description: "Crisp cotton poplin button-front shirt in a relaxed fit. Curved hem for versatile tucking.",
    price: 29.90,
    images: ["https://placehold.co/600x800?text=Poplin+Shirt"],
    stock: 85,
    category: ["women"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "strapless-corset-top",
    name: "Strapless Corset Top",
    brand: "Rotate",
    description: "Structured corset-style top with boning and a zip back. Pairs perfectly with high-waist trousers.",
    price: 168.00,
    originalPrice: 210.00,
    images: ["https://placehold.co/600x800?text=Corset+Top"],
    stock: 12,
    category: ["women", "sale"],
    sizes: ["XS", "S", "M", "L"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "wrap-midi-skirt",
    name: "Wrap Midi Skirt",
    brand: "Faithfull the Brand",
    description: "Tie-front wrap midi skirt in a crinkled cotton. Flattering silhouette with a slight ruffle hem.",
    price: 158.00,
    images: ["https://placehold.co/600x800?text=Wrap+Midi+Skirt"],
    stock: 16,
    category: ["women", "new-arrivals"],
    sizes: ["XS", "S", "M", "L"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "chunky-knit-cardigan",
    name: "Chunky Knit Cardigan",
    brand: "Madewell",
    description: "Oversized chunky-knit open-front cardigan. Cozy ribbed texture with side pockets.",
    price: 118.00,
    images: ["https://placehold.co/600x800?text=Chunky+Cardigan"],
    stock: 21,
    category: ["women"],
    sizes: ["XS/S", "M/L", "XL/XXL"],
    tag: null,
    isPublished: true,
  },

  // Men (35 items)
  {
    slug: "linen-shirt-men",
    name: "Relaxed Linen Shirt",
    brand: "Sunspel",
    description: "Washed linen shirt in a relaxed silhouette. Garment-dyed for a lived-in look with genuine patch pockets.",
    price: 130.00,
    images: ["https://placehold.co/600x800?text=Linen+Shirt+Men"],
    stock: 38,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "slim-taper-jeans-men",
    name: "Slim Taper Jeans",
    brand: "Nudie Jeans",
    description: "Slim taper organic denim in a mid-wash indigo. Slim from hip to knee, tapered to the ankle.",
    price: 155.00,
    images: ["https://placehold.co/600x800?text=Slim+Taper+Jeans"],
    stock: 30,
    category: ["men"],
    sizes: ["28", "29", "30", "31", "32", "33", "34", "36"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "quarter-zip-fleece",
    name: "Quarter Zip Fleece",
    brand: "Patagonia",
    description: "Classic Better Sweater quarter-zip fleece in a plush anti-pill fleece. Zip chest pocket with chest logo.",
    price: 139.00,
    originalPrice: 169.00,
    images: ["https://placehold.co/600x800?text=Fleece+Quarter+Zip"],
    stock: 33,
    category: ["men", "sale"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "tailored-wool-trousers",
    name: "Tailored Wool Trousers",
    brand: "Cos",
    description: "Slim tailored trousers in a lightweight wool blend. Clean front with a slim leg and no-break hem.",
    price: 145.00,
    images: ["https://placehold.co/600x800?text=Wool+Trousers"],
    stock: 20,
    category: ["men"],
    sizes: ["28", "30", "32", "34", "36"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "graphic-sweatshirt-men",
    name: "Graphic Crewneck Sweatshirt",
    brand: "Stussy",
    description: "Heavyweight fleece crewneck with an archival graphic print. Garment-dyed for a soft, faded look.",
    price: 110.00,
    images: ["https://placehold.co/600x800?text=Graphic+Sweatshirt"],
    stock: 40,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "stretch-polo-men",
    name: "Stretch Cotton Polo",
    brand: "Lacoste",
    description: "The classic L.12.12 polo in a performance pique with 4-way stretch. Moisture-wicking finish.",
    price: 89.00,
    images: ["https://placehold.co/600x800?text=Stretch+Polo"],
    stock: 55,
    category: ["men"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "bomber-jacket-men",
    name: "Nylon Bomber Jacket",
    brand: "Alpha Industries",
    description: "The original MA-1 bomber in durable nylon. Distinctive orange lining with a ribbed collar and hem.",
    price: 165.00,
    originalPrice: 200.00,
    images: ["https://placehold.co/600x800?text=Bomber+Jacket"],
    stock: 18,
    category: ["men", "sale"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "henley-shirt-men",
    name: "Long Sleeve Henley",
    brand: "James Perse",
    description: "Relaxed henley in a supima cotton jersey. Three-button placket with a loose, comfortable fit.",
    price: 95.00,
    images: ["https://placehold.co/600x800?text=Henley+Shirt"],
    stock: 45,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "wax-cotton-jacket",
    name: "Wax Cotton Field Jacket",
    brand: "Barbour",
    description: "Iconic Bedale wax jacket in weather-resistant wax cotton. Corduroy collar and genuine brass hardware.",
    price: 359.00,
    images: ["https://placehold.co/600x800?text=Wax+Jacket"],
    stock: 10,
    category: ["men"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "swim-shorts-printed",
    name: "Printed Swim Shorts",
    brand: "Vilebrequin",
    description: "Luxury printed swim shorts in a quick-dry microfibre. Elasticated waist with drawstring and side pockets.",
    price: 225.00,
    originalPrice: 285.00,
    images: ["https://placehold.co/600x800?text=Swim+Shorts"],
    stock: 22,
    category: ["men", "sale"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "white-t-shirt-men",
    name: "Premium White T-Shirt",
    brand: "Sunspel",
    description: "The definitive white tee in a sea island cotton jersey. Slightly longer length with a refined fit.",
    price: 75.00,
    images: ["https://placehold.co/600x800?text=White+Tee"],
    stock: 90,
    category: ["men"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "wide-leg-trousers-men",
    name: "Wide Leg Pleated Trousers",
    brand: "Lemaire",
    description: "Generous wide-leg trousers with a double pleat. Fluid drape in a lightweight cotton-linen blend.",
    price: 380.00,
    images: ["https://placehold.co/600x800?text=Wide+Leg+Trousers"],
    stock: 8,
    category: ["men", "new-arrivals"],
    sizes: ["28", "30", "32", "34", "36"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "corduroy-shirt-jacket",
    name: "Corduroy Shirt Jacket",
    brand: "Pendleton",
    description: "Heritage corduroy shirt jacket in a fine wale. Chest and side pockets with a traditional plaid lining.",
    price: 148.00,
    originalPrice: 185.00,
    images: ["https://placehold.co/600x800?text=Corduroy+Jacket"],
    stock: 14,
    category: ["men", "sale"],
    sizes: ["S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "sport-shorts-men",
    name: "Athletic Sport Shorts",
    brand: "Nike",
    description: "Lightweight Dri-FIT sport shorts with a 7-inch inseam. Side pockets with a brief liner.",
    price: 45.00,
    images: ["https://placehold.co/600x800?text=Sport+Shorts"],
    stock: 75,
    category: ["men"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "wool-overcoat-men",
    name: "Wool Overcoat",
    brand: "Theory",
    description: "Clean-lined double-breasted overcoat in a premium Italian wool. Notch lapels and flap pockets.",
    price: 695.00,
    images: ["https://placehold.co/600x800?text=Wool+Overcoat"],
    stock: 7,
    category: ["men"],
    sizes: ["S", "M", "L", "XL"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "denim-sherpa-jacket",
    name: "Sherpa Lined Denim Jacket",
    brand: "Levi's",
    description: "The Trucker jacket with a warm sherpa lining. Vintage wash denim with a cozy contrast collar.",
    price: 128.00,
    images: ["https://placehold.co/600x800?text=Sherpa+Jacket"],
    stock: 20,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "chore-coat-men",
    name: "Canvas Chore Coat",
    brand: "Carhartt WIP",
    description: "Work-inspired chore coat in a washed canvas. Four external pockets with clean raw-edge lining.",
    price: 175.00,
    originalPrice: 215.00,
    images: ["https://placehold.co/600x800?text=Chore+Coat"],
    stock: 16,
    category: ["men", "sale"],
    sizes: ["S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "knit-shorts-men",
    name: "Terry Knit Shorts",
    brand: "Our Legacy",
    description: "Relaxed terry-knit shorts with a drawstring waist. Soft loop fabric and a straight-leg silhouette.",
    price: 145.00,
    images: ["https://placehold.co/600x800?text=Terry+Shorts"],
    stock: 18,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "puffer-jacket-men",
    name: "Down Puffer Jacket",
    brand: "Canada Goose",
    description: "700-fill power white duck down jacket with a Arctic Tech shell. Windproof and waterproof.",
    price: 650.00,
    images: ["https://placehold.co/600x800?text=Puffer+Jacket"],
    stock: 9,
    category: ["men"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "drawstring-linen-pants",
    name: "Drawstring Linen Pants",
    brand: "Frescobol Carioca",
    description: "Relaxed linen trousers with a drawstring waist. Perfect for warm-weather dressing.",
    price: 120.00,
    originalPrice: 155.00,
    images: ["https://placehold.co/600x800?text=Linen+Pants"],
    stock: 25,
    category: ["men", "sale"],
    sizes: ["S", "M", "L", "XL"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "cable-knit-sweater-men",
    name: "Fisherman Cable Knit",
    brand: "Inis Meain",
    description: "Traditional aran cable-knit sweater hand-crafted in Ireland. 100% merino wool with a crew neck.",
    price: 375.00,
    images: ["https://placehold.co/600x800?text=Cable+Knit"],
    stock: 6,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "track-pants-men",
    name: "Tapered Track Pants",
    brand: "Adidas Originals",
    description: "Classic 3-stripe track pants in a smooth tricot. Tapered leg with a snap-button cuff.",
    price: 75.00,
    images: ["https://placehold.co/600x800?text=Track+Pants"],
    stock: 48,
    category: ["men"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "suede-chukka-boots",
    name: "Suede Chukka Boots",
    brand: "Clarks Originals",
    description: "The iconic Desert Boot in a supple sand suede. Crepe sole and clean two-eyelet lacing.",
    price: 165.00,
    originalPrice: 200.00,
    images: ["https://placehold.co/600x800?text=Chukka+Boots"],
    stock: 14,
    category: ["men", "sale"],
    sizes: ["40", "41", "42", "43", "44", "45", "46"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "band-collar-shirt-men",
    name: "Band Collar Shirt",
    brand: "Margaret Howell",
    description: "Clean band-collar shirt in a crisp cotton poplin. Box pleat at the back for ease of movement.",
    price: 195.00,
    images: ["https://placehold.co/600x800?text=Band+Collar+Shirt"],
    stock: 12,
    category: ["men"],
    sizes: ["S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "relaxed-hoodie-men",
    name: "Essential Relaxed Hoodie",
    brand: "Colorful Standard",
    description: "Heavy-weight organic cotton hoodie in an oversized fit. Kangaroo pocket and a double-layered hood.",
    price: 105.00,
    images: ["https://placehold.co/600x800?text=Relaxed+Hoodie"],
    stock: 50,
    category: ["men", "new-arrivals"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tag: "New",
    isPublished: true,
  },

  // Accessories (25 items)
  {
    slug: "bucket-hat",
    name: "Canvas Bucket Hat",
    brand: "New Era",
    description: "Classic structured bucket hat in a durable cotton canvas. Ventilation eyelets and a wide brim.",
    price: 38.00,
    images: ["https://placehold.co/600x800?text=Bucket+Hat"],
    stock: 60,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "leather-belt-tan",
    name: "Tan Leather Belt",
    brand: "Anderson's",
    description: "Handcrafted full-grain leather belt in a warm tan. 3cm width with a solid brass pin buckle.",
    price: 85.00,
    images: ["https://placehold.co/600x800?text=Tan+Belt"],
    stock: 40,
    category: ["accessories"],
    sizes: ["S", "M", "L", "XL"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "canvas-messenger-bag",
    name: "Canvas Messenger Bag",
    brand: "Eastpak",
    description: "Durable waxed canvas messenger bag with a padded laptop sleeve. Adjustable crossbody strap.",
    price: 72.00,
    originalPrice: 95.00,
    images: ["https://placehold.co/600x800?text=Messenger+Bag"],
    stock: 25,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "minimalist-watch",
    name: "Minimalist Leather Watch",
    brand: "MVMT",
    description: "Clean-dial minimalist watch with a genuine leather strap. 40mm case with sapphire crystal glass.",
    price: 135.00,
    images: ["https://placehold.co/600x800?text=Minimalist+Watch"],
    stock: 20,
    category: ["accessories", "new-arrivals"],
    sizes: ["One Size"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "cashmere-beanie",
    name: "Cashmere Beanie",
    brand: "Johnstons of Elgin",
    description: "Pure cashmere ribbed beanie. Incredibly soft and warm — a winter essential.",
    price: 95.00,
    originalPrice: 125.00,
    images: ["https://placehold.co/600x800?text=Cashmere+Beanie"],
    stock: 30,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "crossbody-mini-bag",
    name: "Mini Crossbody Bag",
    brand: "Polene",
    description: "Structured mini crossbody in a grained leather. Top-handle and chain shoulder strap.",
    price: 185.00,
    images: ["https://placehold.co/600x800?text=Mini+Crossbody"],
    stock: 12,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "silk-hair-scrunchie",
    name: "Silk Hair Scrunchie Set",
    brand: "Slip",
    description: "Set of three pure mulberry silk scrunchies. Gentle on hair and ultra-smooth — no kinks or breakage.",
    price: 45.00,
    images: ["https://placehold.co/600x800?text=Silk+Scrunchies"],
    stock: 80,
    category: ["accessories", "new-arrivals"],
    sizes: ["One Size"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "weekend-duffel-bag",
    name: "Canvas Weekend Duffel",
    brand: "L.L.Bean",
    description: "Rugged open-top duffel in a water-resistant canvas. Interior zip pocket and detachable shoulder strap.",
    price: 89.00,
    originalPrice: 115.00,
    images: ["https://placehold.co/600x800?text=Duffel+Bag"],
    stock: 18,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "aviator-sunglasses",
    name: "Classic Aviator Sunglasses",
    brand: "Ray-Ban",
    description: "The iconic RB3025 aviator with gold metal frame and gradient lenses. UV400 protection.",
    price: 155.00,
    images: ["https://placehold.co/600x800?text=Aviator+Sunglasses"],
    stock: 35,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "gold-hoop-earrings",
    name: "Gold Hoop Earrings",
    brand: "Missoma",
    description: "18k gold-plated sterling silver hoop earrings, 30mm diameter. Lightweight with a secure hinge closure.",
    price: 65.00,
    images: ["https://placehold.co/600x800?text=Gold+Hoops"],
    stock: 45,
    category: ["accessories", "new-arrivals"],
    sizes: ["One Size"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "canvas-backpack",
    name: "Waxed Canvas Backpack",
    brand: "Filson",
    description: "Rugged waxed canvas backpack with a clamshell opening. Padded straps and a 22L capacity.",
    price: 195.00,
    originalPrice: 245.00,
    images: ["https://placehold.co/600x800?text=Canvas+Backpack"],
    stock: 15,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "knit-socks-pack",
    name: "Merino Sock 3-Pack",
    brand: "Falke",
    description: "Three pairs of merino wool socks in a gift box. Temperature-regulating with reinforced heel and toe.",
    price: 42.00,
    images: ["https://placehold.co/600x800?text=Merino+Socks"],
    stock: 70,
    category: ["accessories"],
    sizes: ["S", "M", "L"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "structured-clutch",
    name: "Structured Evening Clutch",
    brand: "Sandro",
    description: "Sleek rectangular clutch in a smooth satin. Gold-tone hardware with a wrist strap.",
    price: 145.00,
    images: ["https://placehold.co/600x800?text=Evening+Clutch"],
    stock: 10,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "reading-glasses",
    name: "Classic Reading Glasses",
    brand: "Warby Parker",
    description: "Lightweight acetate reading glasses in a classic round frame. Comes with a cleaning cloth and case.",
    price: 95.00,
    images: ["https://placehold.co/600x800?text=Reading+Glasses"],
    stock: 28,
    category: ["accessories", "new-arrivals"],
    sizes: ["One Size"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "keychain-leather",
    name: "Leather Keychain Fob",
    brand: "Il Bisonte",
    description: "Hand-stitched vegetable-tanned leather keychain. Ages beautifully with a natural patina.",
    price: 38.00,
    originalPrice: 52.00,
    images: ["https://placehold.co/600x800?text=Leather+Keychain"],
    stock: 55,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "card-holder-slim",
    name: "Slim Card Holder",
    brand: "Common Projects",
    description: "Minimalist card holder in full-grain calf leather. Holds 4–6 cards with a clean flush edge.",
    price: 120.00,
    images: ["https://placehold.co/600x800?text=Card+Holder"],
    stock: 30,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "silk-necktie",
    name: "Silk Woven Necktie",
    brand: "Hermès",
    description: "Hand-rolled silk twill necktie in a classic 7.5cm width. Printed with an original motif.",
    price: 195.00,
    images: ["https://placehold.co/600x800?text=Silk+Necktie"],
    stock: 8,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "tote-canvas-organic",
    name: "Organic Cotton Tote",
    brand: "Baggu",
    description: "Lightweight ripstop nylon tote that folds into a small pouch. Carries up to 50 lbs.",
    price: 12.00,
    images: ["https://placehold.co/600x800?text=Organic+Tote"],
    stock: 200,
    category: ["accessories", "new-arrivals"],
    sizes: ["One Size"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "silver-chain-necklace",
    name: "Sterling Silver Chain Necklace",
    brand: "Mejuri",
    description: "Delicate sterling silver figaro chain necklace, 45cm. Perfect for layering or wearing solo.",
    price: 68.00,
    originalPrice: 88.00,
    images: ["https://placehold.co/600x800?text=Silver+Necklace"],
    stock: 40,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "leather-gloves-men",
    name: "Leather Dress Gloves",
    brand: "Dents",
    description: "Classic unlined leather dress gloves in a smooth hairsheep. Elegant pique stitch detail.",
    price: 95.00,
    images: ["https://placehold.co/600x800?text=Leather+Gloves"],
    stock: 22,
    category: ["accessories"],
    sizes: ["S", "M", "L"],
    tag: "Bestseller",
    isPublished: true,
  },
  {
    slug: "wide-brim-straw-hat",
    name: "Wide Brim Straw Hat",
    brand: "Maison Michel",
    description: "Classic wide-brim straw hat with a grosgrain ribbon band. Hand-woven in Italy.",
    price: 285.00,
    images: ["https://placehold.co/600x800?text=Straw+Hat"],
    stock: 10,
    category: ["accessories", "new-arrivals"],
    sizes: ["S/M", "L/XL"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "gym-duffle-men",
    name: "Nylon Gym Duffel",
    brand: "Aer",
    description: "Compact gym duffel in a ballistic nylon. Separate shoe compartment and a padded laptop sleeve.",
    price: 135.00,
    originalPrice: 165.00,
    images: ["https://placehold.co/600x800?text=Gym+Duffel"],
    stock: 17,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
  {
    slug: "silk-eye-mask",
    name: "Silk Sleep Eye Mask",
    brand: "Slip",
    description: "Pure mulberry silk sleep mask with an adjustable strap. Blocks 99% of light without pressing on eyes.",
    price: 50.00,
    images: ["https://placehold.co/600x800?text=Sleep+Mask"],
    stock: 60,
    category: ["accessories"],
    sizes: ["One Size"],
    tag: null,
    isPublished: true,
  },
  {
    slug: "bifold-wallet",
    name: "Bifold Leather Wallet",
    brand: "Bellroy",
    description: "Slim bifold wallet in premium vegetable-tanned leather. 8 card slots, bill compartment, and coin pocket.",
    price: 79.00,
    images: ["https://placehold.co/600x800?text=Bifold+Wallet"],
    stock: 35,
    category: ["accessories", "new-arrivals"],
    sizes: ["One Size"],
    tag: "New",
    isPublished: true,
  },
  {
    slug: "canvas-phone-strap",
    name: "Canvas Phone Crossbody Strap",
    brand: "Bandolier",
    description: "Adjustable canvas crossbody strap with a universal phone case. Ideal hands-free solution.",
    price: 42.00,
    originalPrice: 58.00,
    images: ["https://placehold.co/600x800?text=Phone+Strap"],
    stock: 45,
    category: ["accessories", "sale"],
    sizes: ["One Size"],
    tag: "Sale",
    isPublished: true,
  },
];

// ── Seed ─────────────────────────────────────────────────────────────────────

async function seed() {
  await mongoose.connect(env.MONGODB_URI);
  console.log("MongoDB connected");

  // Find or create a seed admin user to use as vendorId
  let admin = await User.findOne({ email: "admin@trendyunique.com" });
  if (!admin) {
    const passwordHash = await bcrypt.hash("Admin1234!", 12);
    admin = await User.create({
      email: "admin@trendyunique.com",
      passwordHash,
      firstName: "Admin",
      lastName: "TrendyUnique",
      role: "admin",
    });
    console.log("Created admin user: admin@trendyunique.com / Admin1234!");
  } else {
    console.log("Admin user already exists, skipping creation");
  }

  const vendorId = admin._id;

  // Insert products, skip duplicates (by slug)
  let inserted = 0;
  let skipped = 0;

  for (const data of PRODUCTS) {
    const exists = await Product.findOne({ slug: data.slug });
    if (exists) {
      console.log(`  ⚠ Skip (already exists): ${data.slug}`);
      skipped++;
      continue;
    }
    await Product.create({ ...data, vendorId });
    console.log(`  ✓ Inserted: ${data.name}`);
    inserted++;
  }

  console.log(`\nDone: ${inserted} inserted, ${skipped} skipped`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
